# Generated by Django 3.2.13 on 2022-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasanku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doughnuts',
            name='general',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='dropdown',
            name='dropdown',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geo',
            name='country',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geo',
            name='district',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geo',
            name='dun',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geo',
            name='parlimen',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='geo',
            name='state',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='links',
            name='general',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pyramid',
            name='general',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='snapshotjson',
            name='general',
            field=models.JSONField(),
        ),
    ]
