# Generated by Django 3.2.13 on 2022-05-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kawasanku', '0002_auto_20220526_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jitter', models.JSONField()),
            ],
        ),
    ]
